version: v1.0
name: Typha
execution_time_limit:
  hours: 2
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Build
    task:
      jobs:
        - name: Build
          commands:
            - checkout
            - make build
  - name: Test
    dependencies:
      - Build
    task:
      jobs: []
    prologue:
      commands:
        - checkout
jobs:
  - name: Tests
    commands:
      - make ci
